const f = ()  =>{

try {
    let a = 0
    // console.log(program)
    console.log("Program ran Successfully")
    return
}
catch(err){
    console.log("This is an error")
    // console.log(p)
}
finally{
    console.log("I Am Good Boy")
    // close the file
    // exit the loop
    // write to the log file
}
}

f()